# To start the containers: docker stack deploy --compose-file docker-kafka-stack.yml kz
# This will start 1 zookeeper container and 1 kafka container

version: '3.2'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - type: volume  # Using this volume so that on reboot of the machine the topics are preserved
        source: zkdata
        target: /opt/zookeeper-3.4.13/data

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.101  # Change the ip address to your local ip address
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_LOG_DIRS: /kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume  # Using this volume so that on reboot of the machine the topics are preserved
        source: kafkalogs
        target: /kafka

volumes:
   zkdata:
   kafkalogs:
